### ISSUE TITLE
Simplify if statement chains

### ISSUE THREAD

**Issue by Mosrod** [googleapis/java-compute#143]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Is your feature request related to a problem? Please describe.**
I'm frustrated when I see a if statement chain that can be simplified.

**Describe the solution you'd like**

Instead of this:
src/main/java/com/google/cloud/compute/v1/AggregatedListNodeGroupsHttpRequest.java 
```
if ("access_token".equals(fieldName)) {
      return access_token;
    }
    if ("callback".equals(fieldName)) {
      return callback;
    }
    if ("fields".equals(fieldName)) {
      return fields;
    }
    if ("filter".equals(fieldName)) {
      return filter;
    }
    if ("includeAllScopes".equals(fieldName)) {
      return includeAllScopes;
    }
    if ("key".equals(fieldName)) {
      return key;
    }
    if ("maxResults".equals(fieldName)) {
      return maxResults;
    }
    if ("orderBy".equals(fieldName)) {
      return orderBy;
    }
    if ("pageToken".equals(fieldName)) {
      return pageToken;
    }
    if ("prettyPrint".equals(fieldName)) {
      return prettyPrint;
    }
    if ("project".equals(fieldName)) {
      return project;
...............
```

Do this:
```
if ("".equals(fieldName)) {
         return access_token;
 try {
         return this.getClass().getField(fieldName);
    } catch (NoSuchFieldException e) {
     }
     return null;
   }

```

**Comment by Mosrod** [comment]
It seems that a large amount of files in this repository have the same issue.

This would probably be a problem with the GAPIC generator.

**Comment by suztomo** [comment]
The code is mostly auto-generated. Also, in general, creating an exception is a costly operation in Java than if-statement.
