### ISSUE TITLE
README.md is inconsistent and incorrect

### ISSUE THREAD

**Issue by swpalmer** [googleapis/java-compute#461]
#### Environment details

README.md is using different version numbers in the Maven example and the Gradle example in the QuickStart section:

The pom.xml has 1.2.0-alpha, which the Gradle example uses, however the Maven example uses 0.120.2-alpha

Later in the Versioning section it his claimed that the project is using semantic versioning with a 0 major version.  Perhaps this is why the Maven example had 0.120.2-alpha, even though it doesn't match the project.

Clearly the major version is not zero and so the claim in the versioning section should be rephrased.

#### Steps to reproduce

Read README.md

**Comment by Neenu1995** [comment]
The README has been updated.
