### ISSUE TITLE
How to configure the compute clients to make use of proxies?

### ISSUE THREAD

**Issue by Jessicawy2333** [googleapis/java-compute#604]
Hi,

We have proxies which can either be -
non-authenticated (configure with proxy host and port), or
authenticated (configure with proxy host and port, as well as username and password).

I have found great working examples to configure proxy for gRPC based clients 
https://github.com/googleapis/google-cloud-java#grpc-clients 
https://github.com/googleapis/java-secretmanager/issues/119#issuecomment-621639453
,which doesn't work for compute clients.

I also tried to customize compute client setting's TransportChannelProvider with InstantiatingHttpJsonChannelProvider(for example for RegionsSettings). Customization accepts ApacheHttpTransport, however due to https://github.com/googleapis/google-http-java-client/issues/1442 this is not a good fit yet.

Can you help with some guidelines how to configure proxy settings for the compute clients? Thanks

**Comment by suztomo** [comment]
Proxy configuration is done in system property: https://github.com/googleapis/google-cloud-java#configuring-a-proxy

Google Cloud client libraries use HTTPS and gRPC in underlying communication with the services. In both protocols, you can configure a proxy using https.proxyHost and (optional) https.proxyPort properties.
