### ISSUE TITLE
Do you have plan bulk start/stop compute engine?

### ISSUE THREAD

**Issue by jaeik7** [googleapis/java-compute#638]
We are developing CMP(cloud management platform).
I am researching cloud vm start/stop functions such as AWS EC2, GCP Compute Engine.
There is function bulk start/stop in AWS SDK but not GCP.
Anyway, do you have plan bulk start/stop function?
If have when can i use it?

**Comment by msampathkumar** [comment]
Hi @jaeik7, Thank you for reaching out!

As of now, there is such a bulk stop/start functionality available from their console UI page -[https://console.cloud.google.com/compute/instances](https://console.cloud.google.com/compute/instances)

As for commands, I have `gcloud` commands prepared for you here. 

```
# To list all instances with zone,running status & other details
gcloud compute instances list

# To start a VM using VM's name & VM's Zone
gcloud compute instances start instance-1 --zone us-central1-a
gcloud compute instances start instance-2 --zone us-central1-a

# To start a VM using VM's name & VM's Zone
gcloud compute instances stop instance-1 --zone us-central1-a
gcloud compute instances stop instance-2 --zone us-central1-a
```

In programatic way or using scripting, you can have a loop & fire multiples stop/start VM requests. Thus you can start or stop VM's concurrently. You can also use Java, Php, Python, Terraform and other supported languages or even API's to do achieve results. Please check out our sample browser for quickly parsing through several read to use code sample for your automations.

* For Java - Compute: https://cloud.google.com/docs/samples?l=java&p=compute

**Couple of suggestions**

1. If you are planning to do these operations for large number of VM's operations, I suggest you to use *services accounts*. One example, from a normal user account it's not generally expected that they start or create 400 VM at once, but from a service accounts, these kind of automations are normal. (My past, personal experience - I believe this is the best practice for AWS or Azure as well)

2. Please do check our other Compute and Serverless services too. Compute VM's are almost great fit for most kinds of use cases but at times simpler services like Cloud Run, App Engine, Kubernetes or just Cloud Function would be a perfect fit for many cases.

In Compute VM's too there are options like Preemptible VM's, VM Scheduling, Instance Groups and Carbon Free VM's.

* https://cloud.google.com/compute/docs/instances/preemptible
* https://cloud.google.com/compute/docs/instances/schedule-instance-start-stop
* https://cloud.google.com/compute/docs/instance-groups
* https://cloud.google.com/sustainability/region-carbon

Please let do reach out if you have any other question.

**Comment by jaeik7** [comment]
Thank you for your reply.
I already know using loop for bulk start/stop. 
Is there no plan of support as java sdk?
like below...
`
StartInstanceRequest startInstanceRequest = StartInstanceRequest.newBuilder()
                .setProject(project)
                .setZone(zone)
                .setInstance("instance-1", "instance-2")
                .build();
`

**Comment by msampathkumar** [comment]
Within Java SDK, as of Feb 2022, no such feature/plans to add it in the near future.
